<?php
/* @var $this Joc_Latch_Block_Index */
?>
<div class="page-title">
    <h1><?php echo $this->__('Latch Settings') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Link Your Account With Latch') ?></h2>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li>
                <label for="latch_token" class="required"><em>*</em><?php echo $this->__('Latch Token') ?></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Latch Token') ?>" class="input-text required-entry" name="latch_token" id="latch_token" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save Token') ?>" class="button left"><span><span><?php echo $this->__('Save Token') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
